version: "3.9"
services:
  ai_agent:
    build:
      context: ..
      dockerfile: ai_agent/Dockerfile
    env_file:
      - ../.env
      - ./.env
    environment:
      - CHAT_MODEL=${CHAT_MODEL:-gpt-4o-mini}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
    volumes:
      - ./outputs:/app/outputs
      - ./rag/data:/app/rag/data
      - ./rag/vectorstore:/app/rag/vectorstore
    command: ["bash", "-lc", "./run.sh"]
